username:
  18310874728
password:
  zhao_19931011.
package:
  "com.smile.gifmaker"
package1:
  "com.kwai.gifshow.beta1"
bundle_id:
  "com.facebook.WebDriverAgentRunner.zhaobx.xctrunner"
device_id:
  "00008030-001E31980C89802E"